"""Natural-language intent layer for the Telegram bot.

Generic text that the deterministic parser shouldn't handle (edits, taxonomy
management, reports, richer phrasings) is routed here. We use the Anthropic model
already used elsewhere in the project (Haiku) with **tool use / function calling**
— the first such usage in the codebase.

Design:
- A single round trip classifies the message and maps names -> ids: the current
  taxonomy, the requesting user's recent expenses, the ART date and the DB schema
  are injected up front so the model can resolve references like "el último de
  verdulería" and pick category/concept filters in one shot.
- MUTATIONS (log/edit expense, create category/subcategory) are returned as
  structured params; the bot confirms (edits/taxonomy) or auto-saves (logging)
  and executes the write with parameterized application code. The model NEVER
  writes the mutation itself.
- READS (reports and edit-targeting) are SELECTs generated by the model and
  executed through ``sqlro.run_readonly`` (SELECT-only, read-only connection,
  statement timeout). For reports we feed rows back as a tool_result so the model
  composes a natural Spanish reply.

``route_intent`` returns a dict describing the outcome; the bot turns that into
messages / inline-confirmation flows. It performs no Telegram I/O itself.
"""

import json
import logging
from datetime import datetime, timedelta, timezone

import anthropic
import llm_usage

import db
import sqlro

logger = logging.getLogger(__name__)

_MODEL = "claude-haiku-4-5-20251001"
_MAX_TOOL_TURNS = 4  # cap the report tool-use loop
BAIRES = timezone(timedelta(hours=-3))  # America/Argentina/Buenos_Aires (fixed offset)


# ── Tool definitions ──────────────────────────────────────────────────────────

_TOOLS = [
    {
        "name": "log_expense",
        "description": (
            "Registrar un gasto NUEVO cuando el usuario describe un gasto en lenguaje "
            "natural (ej. 'anotame 100 lucas en el súper', 'gasté 5000 en nafta'). "
            "No usar para modificar un gasto ya registrado (para eso está edit_expense)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "concept": {"type": "string", "description": "Concepto corto del gasto, ej. 'Supermercado', 'Nafta'."},
                "amount": {
                    "type": "number",
                    "description": (
                        "Monto en pesos como número. Interpretá 'lucas'/'luca' como miles "
                        "(100 lucas = 100000) y 'palo'/'palos' como millones. Formato argentino: "
                        "el punto es separador de miles y la coma es decimal."
                    ),
                },
                "currency": {"type": "string", "enum": ["ARS", "USD"], "description": "ARS por defecto; USD solo si el usuario lo aclaró explícitamente."},
                "date": {"type": "string", "description": "Fecha del gasto YYYY-MM-DD (zona ART). Omitir si es hoy."},
                "category": {"type": "string", "description": "Nombre de una categoría EXISTENTE si el usuario la menciona explícitamente. Omitir para que el sistema la infiera."},
                "subcategory": {"type": "string", "description": "Nombre de una subcategoría EXISTENTE si corresponde."},
            },
            "required": ["concept", "amount"],
        },
    },
    {
        "name": "edit_expense",
        "description": (
            "Editar un gasto EXISTENTE del usuario (monto, concepto, categoría, subcategoría o fecha). "
            "Usar cuando el usuario corrige o cambia un gasto ya registrado "
            "(ej. 'el último gasto fueron 90000', 'en el último de verdulería poné 30000', "
            "'el gasto 124: total 40000 y categoría nafta')."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "target_sql": {
                    "type": "string",
                    "description": (
                        "Consulta SQL SELECT de solo lectura que devuelva la columna id de los gastos "
                        "candidatos, SIEMPRE filtrada por user_id igual al ID del usuario que pregunta. "
                        "Usá la taxonomía para decidir si un término filtra por concepto (concept LIKE) o "
                        "por categoría (category_id). Para 'el último' ordená por created_at DESC LIMIT 1. "
                        "Ejemplo: SELECT id FROM expenses WHERE user_id = 3 AND category_id = 5 "
                        "ORDER BY created_at DESC LIMIT 1"
                    ),
                },
                "changes": {
                    "type": "object",
                    "description": "Solo los campos que el usuario pidió cambiar.",
                    "properties": {
                        "amount": {"type": "number", "description": "Nuevo monto en la moneda nativa del gasto."},
                        "currency": {"type": "string", "enum": ["ARS", "USD"], "description": "Nueva moneda; no cambiar si el gasto está vinculado a un fijo."},
                        "concept": {"type": "string"},
                        "category": {"type": "string", "description": "Nombre de categoría (puede no existir todavía)."},
                        "subcategory": {"type": "string"},
                        "date": {"type": "string", "description": "YYYY-MM-DD (zona ART)."},
                        "fixed_expense": {
                            "type": "string",
                            "description": (
                                "Nombre de un gasto fijo EXISTENTE para vincular este gasto "
                                "(ej. 'poné que esto es el pago del alquiler'). Usá 'ninguno' "
                                "si el usuario pide desvincularlo. No inventes gastos fijos que "
                                "no existen."
                            ),
                        },
                    },
                },
            },
            "required": ["target_sql", "changes"],
        },
    },
    {
        "name": "create_category",
        "description": "Crear una nueva categoría de nivel superior (ej. 'agregá la categoría Niños').",
        "input_schema": {
            "type": "object",
            "properties": {"name": {"type": "string"}},
            "required": ["name"],
        },
    },
    {
        "name": "create_subcategory",
        "description": (
            "Crear una subcategoría dentro de una categoría existente "
            "(ej. 'en la categoría Casa agregá la subcategoría Productos de limpieza')."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "parent_category": {"type": "string", "description": "Nombre de la categoría madre existente."},
                "name": {"type": "string"},
            },
            "required": ["parent_category", "name"],
        },
    },
    {
        "name": "run_report",
        "description": (
            "Ejecutar una consulta SQL SELECT de solo lectura para responder una pregunta o reporte "
            "sobre los gastos (ej. 'cuánto gasté esta semana', 'mi categoría más cara del trimestre', "
            "'cuánto gastó Cele en comida en marzo'). Los reportes ven los gastos de TODA la familia. "
            "Devuelve las filas para que las resumas en una respuesta clara en español."
        ),
        "input_schema": {
            "type": "object",
            "properties": {"sql": {"type": "string", "description": "Consulta SELECT de solo lectura sobre el esquema dado."}},
            "required": ["sql"],
        },
    },
]

_SCHEMA_DOC = (
    "Esquema PostgreSQL (solo lectura):\n"
    "  expenses(id, user_id, category_id, subcategory_id, concept TEXT, amount NUMERIC, currency TEXT, raw_text TEXT, created_at TIMESTAMPTZ)\n"
    "  users(id, telegram_id, name, color)\n"
    "  categories(id, name, color, icon)\n"
    "  subcategories(id, category_id, name)\n"
    "Notas:\n"
    "  - created_at es TIMESTAMPTZ almacenado en UTC. Para día/semana/mes argentino usá "
    "(created_at AT TIME ZONE 'America/Argentina/Buenos_Aires').\n"
    "  - Usá sintaxis PostgreSQL: EXTRACT, date_trunc, to_char e INTERVAL; nunca funciones SQLite.\n"
    "  - category_id y subcategory_id pueden ser NULL (gasto sin categorizar).\n"
    "  - currency es ARS o USD; amount está en su moneda nativa. Nunca sumes ni compares directamente monedas distintas: filtrá por currency o agrupá por currency."
)


# ── Context builders ──────────────────────────────────────────────────────────

def _build_system_prompt(user) -> str:
    now = datetime.now(BAIRES)
    cats = db.get_all_categories()
    subs = db.get_all_subcategories()
    users = db.get_all_users()
    recent = db.get_recent_expenses_for_user(user["id"], limit=30)

    cat_lines = "\n".join(f"  - id={c['id']}: {c['name']}" for c in cats) or "  (ninguna)"
    sub_lines = "\n".join(
        f"  - id={s['id']}: {s['name']} (categoría: {s['category_name']}, category_id={s['category_id']})"
        for s in subs
    ) or "  (ninguna)"
    user_lines = "\n".join(f"  - id={u['id']}: {u['name']}" for u in users) or "  (ninguno)"

    recent_lines = []
    for e in recent:
        local = _to_art(e["created_at"])
        recent_lines.append(
            f"  - id={e['id']} | {local} | {e['concept']} | {e['currency']} {e['amount']:.0f} | "
            f"{e['category_name']}" + (f" / {e['subcategory_name']}" if e["subcategory_name"] else "")
        )
    recent_block = "\n".join(recent_lines) or "  (sin gastos recientes)"

    return (
        "Sos el asistente de un bot de gastos familiar por Telegram. Interpretás mensajes en "
        "español rioplatense y elegís UNA herramienta para actuar, o respondés directamente en "
        "texto si el mensaje es una aclaración/saludo o no se entiende (pedí que reformule).\n\n"
        f"Fecha y hora actual (Argentina): {now.strftime('%Y-%m-%d %H:%M')} ({now.strftime('%A')}).\n"
        "Usá la zona America/Argentina/Buenos_Aires (UTC-3) para 'hoy', 'esta semana', 'este mes', "
        "'marzo', 'el trimestre', etc.\n"
        "Formato numérico argentino: el punto es separador de miles y la coma es decimal. "
        "'lucas'/'luca' = miles, 'palo'/'palos' = millones.\n\n"
        "Monedas: ARS es el valor por defecto. Si el mensaje dice USD, US$, U$S o dólares, usá USD. "
        "En reportes SQL, NUNCA sumes monedas mezcladas: filtrá por currency o GROUP BY currency.\n\n"
        f"El usuario que escribe es: id={user['id']}, nombre={user['name']}.\n\n"
        "Categorías:\n" + cat_lines + "\n\n"
        "Subcategorías:\n" + sub_lines + "\n\n"
        "Usuarios de la familia:\n" + user_lines + "\n\n"
        "Últimos gastos de este usuario (para resolver 'el último', etc.):\n" + recent_block + "\n\n"
        + _SCHEMA_DOC + "\n\n"
        "Reglas:\n"
        "  - Para registrar un gasto nuevo: log_expense.\n"
        "  - Para modificar un gasto ya registrado: edit_expense, con un target_sql que devuelva "
        "el/los id candidatos SIEMPRE filtrado por user_id=" + str(user["id"]) + " (un usuario solo "
        "puede editar SUS propios gastos).\n"
        "  - Para crear categorías/subcategorías: create_category / create_subcategory.\n"
        "  - Para consultas/reportes de solo lectura: run_report (SELECT único). Los reportes ven a "
        "toda la familia.\n"
        "  - Nunca inventes ids de categoría/subcategoría: usá los de arriba. Si el usuario menciona "
        "una categoría que no existe en una edición, igual pasala por nombre en 'changes.category' "
        "(el sistema ofrecerá crearla).\n"
        "  - Emití SIEMPRE consultas SELECT de solo lectura; nunca INSERT/UPDATE/DELETE.\n"
        "  - Tenés memoria de los mensajes de los últimos 5 minutos de este chat (ya incluidos como "
        "turnos previos si corresponde). Si el mensaje actual depende de algo dicho antes de esa "
        "ventana, o de una conversación que no ves en tu contexto, no asumas nada ni inventes un "
        "dato: pedile al usuario que repita la pregunta completa."
    )


def _to_art(created_at: str) -> str:
    """Convert a stored UTC timestamp string to an ART date/time string for display."""
    try:
        dt = datetime.strptime(created_at, "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        return dt.astimezone(BAIRES).strftime("%Y-%m-%d %H:%M")
    except (ValueError, TypeError):
        return str(created_at)


# ── Result helpers ────────────────────────────────────────────────────────────

def _reply(text: str) -> dict:
    return {"kind": "reply", "text": text}


def _first_tool_use(message):
    for block in message.content:
        if getattr(block, "type", None) == "tool_use":
            return block
    return None


def _joined_text(message) -> str:
    parts = [getattr(b, "text", "") for b in message.content if getattr(b, "type", None) == "text"]
    return "\n".join(p for p in parts if p).strip()


def _extract_ids(rows: list[dict]) -> list[int]:
    ids = []
    for r in rows:
        val = r.get("id") if "id" in r else (next(iter(r.values()), None) if r else None)
        try:
            ids.append(int(val))
        except (TypeError, ValueError):
            continue
    return ids


# ── Entry point ───────────────────────────────────────────────────────────────

def route_intent(text: str, user, anthropic_api_key: str, history: list | None = None) -> dict:
    """Classify and act on a free-text message. Returns a dict with a 'kind':
      - {"kind":"log", "concept","amount","date","category","subcategory"}
      - {"kind":"edit", "candidate_ids":[int], "changes":{...}}
      - {"kind":"category", "name"}
      - {"kind":"subcategory", "parent","name"}
      - {"kind":"report", "text"}   (Spanish reply already composed)
      - {"kind":"reply", "text"}    (clarification / free text)
      - {"kind":"error", "text"}

    ``history`` is an optional list of prior {"role": "user"/"assistant", "content": str}
    turns (a short rolling window kept by the caller) prepended before the current
    message, so the model can resolve short-lived follow-ups ("dame el desglose",
    "sí, por persona") within that window. Performs no Telegram I/O; the bot turns
    the result into messages/confirmation flows.
    """
    try:
        client = anthropic.Anthropic(api_key=anthropic_api_key, timeout=20.0, max_retries=0)
        system = _build_system_prompt(user)
    except Exception as e:
        logger.error("Error preparando intent layer: %s", e)
        return {"kind": "error", "text": "⚠️ No pude procesar el mensaje. Probá de nuevo."}

    messages = [{"role": h["role"], "content": h["content"]} for h in (history or [])]
    messages.append({"role": "user", "content": text})

    try:
        for _ in range(_MAX_TOOL_TURNS):
            call_started = llm_usage.started()
            try:
                message = client.messages.create(
                    model=_MODEL,
                    max_tokens=1024,
                    system=system,
                    tools=_TOOLS,
                    messages=messages,
                )
            except Exception as e:
                llm_usage.record("intent", _MODEL, call_started, error=e)
                raise
            llm_usage.record("intent", _MODEL, call_started, response=message)

            tool = _first_tool_use(message)
            if tool is None:
                # No tool call: treat any text as a direct reply.
                reply = _joined_text(message)
                return _reply(reply or "🤔 No te entendí. ¿Podés reformularlo?")

            name = tool.name
            args = tool.input or {}

            if name == "log_expense":
                return _handle_log(args)
            if name == "edit_expense":
                return _handle_edit(args, user)
            if name == "create_category":
                return _handle_create_category(args)
            if name == "create_subcategory":
                return _handle_create_subcategory(args)
            if name == "run_report":
                # Read-only loop: execute SELECT, feed rows back, let the model compose.
                tool_result = _run_report_sql(args.get("sql", ""))
                messages.append({"role": "assistant", "content": message.content})
                messages.append({
                    "role": "user",
                    "content": [{
                        "type": "tool_result",
                        "tool_use_id": tool.id,
                        "content": tool_result,
                    }],
                })
                continue

            # Unknown tool name — shouldn't happen.
            return _reply("🤔 No te entendí. ¿Podés reformularlo?")

        # Ran out of turns without a final answer.
        return _reply("🤔 No pude completar la consulta. ¿Podés reformularla?")
    except Exception as e:
        logger.error("Error en intent layer: %s", e)
        return {"kind": "error", "text": "⚠️ Hubo un error interpretando el mensaje. Probá de nuevo."}


def _handle_log(args: dict) -> dict:
    try:
        amount = float(args.get("amount"))
    except (TypeError, ValueError):
        return _reply("🤔 No me quedó claro el monto. ¿Me lo repetís?")
    if amount <= 0:
        return _reply("🤔 No me quedó claro el monto. ¿Me lo repetís?")
    concept = (args.get("concept") or "").strip()
    if not concept:
        return _reply("🤔 ¿Qué concepto le pongo al gasto?")
    return {
        "kind": "log",
        "concept": concept,
        "amount": amount,
        "currency": db.normalize_currency(args.get("currency")),
        "date": (args.get("date") or "").strip() or None,
        "category": (args.get("category") or "").strip() or None,
        "subcategory": (args.get("subcategory") or "").strip() or None,
    }


def _handle_edit(args: dict, user) -> dict:
    target_sql = args.get("target_sql", "")
    changes = args.get("changes") or {}
    # Normalize changes to a clean dict.
    clean: dict = {}
    if changes.get("amount") is not None:
        try:
            amt = float(changes["amount"])
            if amt > 0:
                clean["amount"] = amt
        except (TypeError, ValueError):
            pass
    if changes.get("currency") is not None:
        try:
            clean["currency"] = db.normalize_currency(changes["currency"])
        except ValueError:
            pass
    for key in ("concept", "category", "subcategory", "date", "fixed_expense"):
        val = changes.get(key)
        if isinstance(val, str) and val.strip():
            clean[key] = val.strip()
    if not clean:
        return _reply("🤔 No entendí qué querés cambiar del gasto.")

    try:
        rows = sqlro.run_readonly(target_sql, max_rows=25)
    except sqlro.ReadOnlySQLError as e:
        logger.warning("edit target_sql rechazado: %s | sql=%s", e, target_sql)
        return _reply("🤔 No pude identificar el gasto. ¿Podés ser más específico?")

    candidate_ids = _extract_ids(rows)
    return {"kind": "edit", "candidate_ids": candidate_ids, "changes": clean}


def _handle_create_category(args: dict) -> dict:
    name = (args.get("name") or "").strip()
    if not name:
        return _reply("🤔 ¿Qué nombre le pongo a la categoría?")
    return {"kind": "category", "name": name}


def _handle_create_subcategory(args: dict) -> dict:
    name = (args.get("name") or "").strip()
    parent = (args.get("parent_category") or "").strip()
    if not name or not parent:
        return _reply("🤔 Decime la categoría madre y el nombre de la subcategoría.")
    return {"kind": "subcategory", "parent": parent, "name": name}


def _run_report_sql(sql: str) -> str:
    """Execute a report SELECT under guardrails and return a compact JSON string
    (rows or error) to feed back to the model as a tool_result."""
    try:
        rows = sqlro.run_readonly(sql, max_rows=200)
    except sqlro.ReadOnlySQLError as e:
        return json.dumps({"error": str(e)}, ensure_ascii=False)
    return json.dumps({"rows": rows}, ensure_ascii=False, default=str)
